# Generated by Django 4.2.2 on 2023-06-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("linkedinapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freelancer",
            name="city",
        ),
        migrations.RemoveField(
            model_name="freelancer",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
