# Generated by Django 4.2.2 on 2023-06-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("linkedinapp", "0002_remove_freelancer_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="hourly_rate",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="jobproposal",
            name="freelancer_hourly_rate",
            field=models.CharField(max_length=10),
        ),
    ]
