# Generated by Django 4.2.2 on 2023-06-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("linkedinapp", "0004_client_user_freelancer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="start_date",
        ),
        migrations.AddField(
            model_name="jobpost",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
