# Generated by Django 4.2.2 on 2023-06-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "linkedinapp",
            "0005_remove_project_end_date_remove_project_start_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("COMPLETED", "Completed"),
                ],
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
