# Generated by Django 4.2.2 on 2023-07-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("linkedinapp", "0006_jobpost_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
